[package]
name = "boatbomber/pixelcolorapproximation"
description = "Rough approximation of pixel colors in Roblox"
version = "0.2.1"
license = "MPL 2.0"
authors = ["boatbomber (https://boatbomber.com)"]
registry = "https://github.com/upliftgames/wally-index"
realm = "shared"
include = ["src", "src/**", "wally.toml", "wally.lock", "default.project.json"]
exclude = ["**"]
